version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: base_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  basebot:
    build: .
    container_name: base_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    command: sh -c "alembic revision --autogenerate -m 'Create a baseline migrations' && alembic upgrade head &&
             python main.py"

volumes:
  postgres_data:
